### PR TITLE
Additional student guidance

### PR DESCRIPTION
**Pull request by l-gorman**
Draft PR to implement changes which need to 
be made before the new members of ask JGI team joint

* [x] Need to provide information on where to store information #17
* [x] Add info on labelling queries #16 
* [x] Remove section on Indico
* [x] General review/update of materials

Further updates to add #19

### CODE REVIEW

**Comment by jatonline** [comment]
Looks good! :) Happy to merge this or if you want to make further changes here following today's meeting then go for it!

**Comment by jatonline** [comment]
@l-gorman as discussed, I've suggested some (minor) changes.

Happy for you to continue with the other things you think are needed:
1. Add some details about the tracker (filling it in etc…)
2. Add new links to the new sharepoint folders
3. Edit the shift organization page so it is accurate for having one shifter on at a time

...with the links to SharePoint, Tracker, Slack, etc. I wonder if it's worth linking to a (newly-created) single page that links to everything external?
- this could be a useful bookmark for people
- and would mean only one place to edit when links change

(See what you think)

I've added @RichardP1234 to review in my absence :)

**Comment by jatonline** [comment]
Based on our group discussion today, we're going to merge this PR as-is now, and open up new issues for any remaining work. :)

Thanks @l-gorman and @RichardP1234 for your help! 🎉

**Comment by l-gorman** [comment]
Thanks @jatonline! Sorry I didn't get round to the final changes 🙌

**Pull request merged**
